trigger:
  branches:
    include:
      - main  # Trigger on changes to the 'main' branch (you can change this to your default branch)

pool:
  name: 'Default'  # Use the latest Ubuntu image for the build pipeline

stages:
- stage: BuildAndDeploy
  jobs:
  - job: DeployToAzure
    steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Servicetest'  # Select your Azure subscription (from Service Connections)
        appName: 'webapp001'  # Name of your Azure App Service
        package: '$(System.DefaultWorkingDirectory)/'  # Points to the root directory of your repository
